# Generated by Django 5.0.2 on 2024-02-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttDetGatTat',
            fields=[
                ('name', models.CharField(blank=True, max_length=30, null=True, primary_key=True, serialize=False)),
                ('att_dt', models.DateField(blank=True, null=True)),
                ('att_typ', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('OO', 'Weekly Off'), ('H', 'Holiday'), ('OH', 'Optional Holiday')], max_length=2, null=True)),
            ],
            options={
                'db_table': 'att_det_gat_tat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttLocnMast',
            fields=[
                ('locn_code', models.IntegerField(primary_key=True, serialize=False)),
                ('locn_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'att_locn_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttMastGatTat',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('zone', models.CharField(blank=True, max_length=5, null=True)),
                ('dept', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('Not Reported', 'Not Reported'), ('Resigned', 'Resigned'), ('Transferred', 'Transferred')], max_length=15, null=True)),
            ],
            options={
                'db_table': 'att_mast_gat_tat',
                'managed': False,
            },
        ),
    ]
